CREATE TABLE IF NOT EXISTS urls (
    urlLoc TEXT PRIMARY KEY NOT NULL,
    visited INTEGER
);

CREATE TABLE IF NOT EXISTS picUrls (
    urlLoc TEXT PRIMARY KEY NOT NULL,
    err TEXT,
    visited INTEGER
);

CREATE TABLE IF NOT EXISTS storedPics (
    shaPicHash TEXT PRIMARY KEY NOT NULL,
    filePath TEXT NOT NULL UNIQUE,
    urlLoc TEXT NOT NULL UNIQUE 
);
